### ISSUE TITLE
不知道为什么会有thread的bug。。。

### ISSUE THREAD

**Issue by Angelinewong0818** [littlecodersh/itchatmp#49]
`/usr/lib/python3/dist-packages/urllib3/connectionpool.py:845: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Uncaught exception POST /?signature=66bd3f677364c353d9b986e4b0005f3e86d2c97f&timestamp=1539071870&nonce=797132558&openid=obYqI1KyGRMh52u_eS1_33pEPYtk (127.0.0.1)
HTTPServerRequest(protocol='http', host='raspberrypitest.natapp1.cc', method='POST', uri='/?signature=66bd3f677364c353d9b986e4b0005f3e86d2c97f&timestamp=1539071870&nonce=797132558&openid=obYqI1KyGRMh52u_eS1_33pEPYtk', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.5/dist-packages/itchatmp/components/register.py", line 231, in post
    r, rawReply = yield threadPool.submit(post_fn, self)
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/itchatmp/components/register.py", line 61, in sync_post_fn
    return verify_reply(core, tns, reply, msgDict, isActualEncrypt)
  File "/usr/local/lib/python3.5/dist-packages/itchatmp/components/register.py", line 165, in verify_reply
    r = core.upload(reply['MsgType'], reply['FileDir'])
  File "/usr/local/lib/python3.5/dist-packages/itchatmp/controllers/messages.py", line 34, in upload
    fileType, fileDir, additionalDict, permanent)
  File "/usr/local/lib/python3.5/dist-packages/itchatmp/controllers/common.py", line 19, in determine_wrapper
    return mpFn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/itchatmp/controllers/mpapi/base/common.py", line 147, in __access_token
    updateResult = tokenFn()
  File "/usr/local/lib/python3.5/dist-packages/itchatmp/controllers/mpapi/base/common.py", line 82, in _update_access_token
    r = ReturnValue(r)
  File "/usr/local/lib/python3.5/dist-packages/itchatmp/returnvalues.py", line 30, in __init__
    Future.__init__(self)
  File "/usr/lib/python3.5/asyncio/futures.py", line 169, in __init__
    self._loop = events.get_event_loop()
  File "/usr/lib/python3.5/asyncio/events.py", line 671, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "/usr/lib/python3.5/asyncio/events.py", line 583, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-1'.
`
我只是想回图片给发过来的人，然后就一直报这个错，感觉像是没办法创建新的进程？
`@itchatmp.msg_register(itchatmp.content.TEXT)
def text_reply(msg):
    print(msg)
    return '@img@image.jpg'

itchatmp.run()`

**Comment by ShenKeeeew** [comment]
我猜你是不是个人订阅号所以没有客服接口的权限
