### ISSUE TITLE
服务器经常出现 TypeError: send() takes at least 2 arguments (1 given)

### ISSUE THREAD

**Issue by ammrwu** [littlecodersh/itchatmp#8]
```python
Uncaught exception POST /?signature=96e4cea608b71070e6a4a71a66d20b38b79dca8b&timestamp=1489068324&nonce=1809922204&openid=ooQn8wMiWdUAPsctsTYI5PcYUL7Y (58.247.206.151)
HTTPServerRequest(protocol='http', host='101.37.24.45', method='POST', uri='/?signature=96e4cea608b71070e6a4a71a66d20b38b79dca8b&timestamp=1489068324&nonce=1809922204&openid=ooQn8wMiWdUAPsctsTYI5PcYUL7Y', version='HTTP/1.1', remote_ip='58.247.206.151', headers={'Content-Length': '277', 'Accept': '*/*', 'User-Agent': 'Mozilla/4.0', 'Host': '101.37.24.45', 'Pragma': 'no-cache', 'Content-Type': 'text/xml'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1469, in _execute
    result = yield result
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "build/bdist.linux-x86_64/egg/itchatmp/components/register.py", line 236, in post
    (rawReply, rawReply.get('ToUserName', '')))
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: send() takes at least 2 arguments (1 given)
```

**Comment by littlecodersh** [comment]
@ammrwu 就报错信息我好像没法看出是哪个send，你更新之后还是会有这个报错吗？
